previewsEnabled: true
databases:
  - name: rails7-example-ohio
    databaseName: rails7example
    user: rails7example
    region: ohio
    postgresMajorVersion: 14

services:
  - type: web
    name: rails7-example-ohio
    env: ruby
    region: ohio
    healthCheckPath: /
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7-example-ohio
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
