previewsEnabled: true
databases:
  - name: rails7-example 
    databaseName: rails7example
    user: rails7example
    postgresMajorVersion: 14

services:
  - type: web
    name: rails7-example
    env: docker 
    dockerfilePath: Dockerfile.render
    # buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    # healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7-example
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
