previewsEnabled: true
databases:
  - name: rails7masterdetaildb
    databaseName: rails7examplemasterdetail
    user: rails7example
    postgresMajorVersion: 14
    region: frankfurt

services:
  - type: web
    name: rails7examplemasterdetail
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7masterdetaildb
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
